-- MySQL Script generated by MySQL Workbench
-- Mon Apr 13 10:05:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `hackathon`;
USE `hackathon` ;

-- -----------------------------------------------------
-- Table `hackathon`.`ideias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`ideias` (
  `id_ideia` INT NOT NULL,
  `nome_autor` VARCHAR(45) NOT NULL,
  `descricao_ideia` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_ideia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`pessoas` (
  `id_pessoa` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `ideias_id_ideia` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `ideias_id_ideia`),
  INDEX `fk_pessoas_ideias_idx` (`ideias_id_ideia` ASC),
  CONSTRAINT `fk_pessoas_ideias`
    FOREIGN KEY (`ideias_id_ideia`)
    REFERENCES `hackathon`.`ideias` (`id_ideia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;